//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaurdedText.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_1
    {
        public string site_url { get; set; }
        public string cipher { get; set; }
        public string hashcontent { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
